### ISSUE TITLE
eth_sendRawTransaction and eth_getBalance keep repeating and failing

### ISSUE THREAD

**Issue by nanjiangwill** [lightclients/kevlar#10]
```
An unexpected error occurred while executing "eth_sendRawTransaction" JSON-RPC method: Error: RPC request failed
    at RPC.<anonymous> (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/@lightclients/kevlar/node_modules/@lightclients/patronum/lib/rpc.js:93:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/@lightclients/kevlar/node_modules/@lightclients/patronum/lib/rpc.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

An unexpected error occurred while executing "eth_getBalance" JSON-RPC method: Error: RPC request failed
    at RPC.<anonymous> (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/@lightclients/kevlar/node_modules/@lightclients/patronum/lib/rpc.js:93:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/.nvm/versions/node/v18.12.1/lib/node_modules/@lightclients/kevlar/node_modules/@lightclients/patronum/lib/rpc.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

these two errors keep showing up, my guess is that wallet will keep calling this rpc and rpc failed without sending error to wallet so that wallet will keep calling.

How to fix this issue? And how to reset?

**Comment by shresthagrawal** [comment]
I am unable to replicate the issue. Can you give more details about your setup? Are you using a custom RPC endpoint?

**Comment by nanjiangwill** [comment]
what I did is to 
`kevlar -p 3000` to start kevlar

and then add this to my network. I did two transactions on Curve and they are still pending while log in kevlar shows the errors above
